import { Controller, Post, Body, UseGuards, BadRequestException } from '@nestjs/common';
import { JournalService } from './journal.service';
import { BlocksService } from '../blocks/blocks.service';
import { ServiceAuthGuard } from '../common/guards/service-auth.guard';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { CurrentUser } from '../auth/current-user.decorator';
import type { AccessTokenPayload } from '@nau/types';

export class GenerateSummaryDto {
  periodType!: 'daily' | 'weekly' | 'monthly' | 'trimester' | 'yearly' | 'custom';
  startDate!: string;
  endDate!: string;
  workspaceId!: string;
}

export class DirectSummaryDto {
  periodType!: 'daily' | 'weekly' | 'monthly' | 'trimester' | 'yearly';
  type!: string; // e.g. 'content_brief'
  synthesis!: string;
  summary!: string;
  startDate!: string;
  endDate!: string;
}

export class CustomSummaryDto {
  startDate!: string;
  endDate!: string;
  workspaceId!: string;
}

/**
 * Guards are per-route rather than on the class.
 *
 * Two of these routes are for services — Zazŭ asking for a summary on command —
 * and one is for a person in the web app asking for a range they picked
 * themselves. A class-level ServiceAuthGuard would have made the third
 * unreachable from a browser, and NestJS composes method and class guards rather
 * than letting the method override.
 */
@Controller('journal')
export class JournalController {
  constructor(
    private readonly journalService: JournalService,
    private readonly blocksService: BlocksService,
  ) {}

  @Post('summary')
  @UseGuards(ServiceAuthGuard)
  async generateSummary(@Body() request: GenerateSummaryDto) {
    if (!request.periodType || !request.startDate || !request.endDate || !request.workspaceId) {
      return {
        success: false,
        error: 'Missing required fields: periodType, startDate, endDate, workspaceId',
      };
    }
    return this.journalService.generateSummary(
      request.periodType,
      request.startDate,
      request.endDate,
      request.workspaceId,
    );
  }

  /**
   * A summary over any range the person picked: a trip, a stretch of weeks, the
   * span of an astrological transit. Distinct from the scheduled periods, which
   * are generated by cron and are idempotent on their own boundaries — a custom
   * range is regenerated on request, because the person asked for it again.
   */
  @Post('summary/custom')
  @UseGuards(JwtAuthGuard)
  async generateCustomSummary(
    @CurrentUser() user: AccessTokenPayload,
    @Body() request: CustomSummaryDto,
  ) {
    const workspaceId = request.workspaceId ?? user.workspaceId;
    if (!request.startDate || !request.endDate || !workspaceId) {
      throw new BadRequestException('startDate, endDate and workspaceId are required');
    }
    // The route takes a workspace id from the body, so membership is checked
    // here rather than assumed — this is the only journal route a browser can
    // reach, and a workspace id is trivially guessable.
    await this.blocksService.assertWorkspaceMembership(user.sub, workspaceId);

    return this.journalService.generateSummary(
      'custom',
      request.startDate,
      request.endDate,
      workspaceId,
    );
  }

  @Post('summary/direct')
  @UseGuards(ServiceAuthGuard)
  async saveDirectSummary(@Body() request: DirectSummaryDto) {
    if (!request.periodType || !request.synthesis || !request.summary || !request.startDate || !request.endDate) {
      return { success: false, error: 'Missing required fields for direct summary' };
    }
    return this.journalService.saveDirectSummary(
      request.periodType,
      request.type || 'journal_summary',
      request.synthesis,
      request.summary,
      request.startDate,
      request.endDate
    );
  }
}
