/**
 * Content format types supported by flownaŭ v2.
 * Determines rendering method and publishing API.
 */
export type ContentFormat =
  | 'reel'
  | 'trial_reel'
  | 'head_talk'
  | 'carousel'
  | 'static_post'
  | 'story'
  | 'replicate' // Phase 18: captured post replicated from 9naŭ (user-managed)

/**
 * Composition status flow:
 * DRAFT → APPROVED → RENDERING → RENDERED → SCHEDULED → PUBLISHING → PUBLISHED
 *                                                                   → FAILED
 */
export type CompositionStatus =
  | 'DRAFT'
  | 'APPROVED'
  | 'RENDERING'
  | 'RENDERED'
  | 'SCHEDULED'
  | 'PUBLISHING'
  | 'PUBLISHED'
  | 'FAILED'

/**
 * Source of a content idea.
 * - internal: Generated by flownaŭ ideation engine
 * - inspo: Derived from nauthenticity InspoItems
 * - user_input: Manual input from user (dashboard, 9naŭ Second Brain)
 * - reactive: Triggered by an external event (9naŭ block creation, echonau triage)
 */
export type IdeaSource = 'internal' | 'inspo' | 'user_input' | 'reactive'

/**
 * Render job status flow:
 * queued → rendering → uploading → done
 *                                → failed
 */
export type RenderJobStatus = 'queued' | 'rendering' | 'uploading' | 'done' | 'failed'
